# Generated by Django 4.0.4 on 2022-06-09 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_answer_answer_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='title',
            new_name='question_text',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='name',
            new_name='quiz_name',
        ),
    ]
