# Generated by Django 4.0.4 on 2022-06-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_rename_title_question_question_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('d', 'Difficult'), ('n', 'Normal'), ('e', 'Easy')], default='', max_length=10),
        ),
    ]
